[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mcp-server-azure-ai-agent"
version = "0.1.0"
description = "Azure AI Agent Service MCP Server"
readme = "README.md"
authors = [
    {name = "Farzad Sunavala", email = "fsunavala@microsoft.com"},
]
license = {text = "MIT"}
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
]
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=1.4.1",
    "azure-identity>=1.21.0",
    "python-dotenv>=1.0.1",
    "azure-ai-projects>=1.0.0b7",
]

[project.urls]
"Homepage" = "https://github.com/modelcontextprotocol/servers"
"Bug Tracker" = "https://github.com/modelcontextprotocol/servers/issues"

[project.scripts]
mcp-server-azure-ai-agent = "mcp_server_azure_ai_agent.__main__:main"
